name: todo_sample_builtvalue
description: Models for the todo_sample application implemented using built value
# version: 1.0.0
# homepage: https://www.example.com
# author: jasperamorgan <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_value: '^6.3.2'
  built_collection: '^4.1.0'

dev_dependencies:
  build_runner: '^1.3.1'
  built_value_generator: '^6.3.2'
  pedantic: '^1.0.0'
  test: '^1.0.0'
  built_value_test: '^6.3.2'
